<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries =   array(
            array("country_code"=>101,"name"=>"الامارات العربية","name_loc"=>"Arab Emirates"),
            array("country_code"=>102,"name"=>"الاردن","name_loc"=>"Jordan"),
            array("country_code"=>103,"name"=>"البحرين","name_loc"=>"Bahrain"),
            array("country_code"=>104,"name"=>"سوريا","name_loc"=>"Syria"),
            array("country_code"=>105,"name"=>"العراق","name_loc"=>"Iraq"),
            array("country_code"=>106,"name"=>"عمان","name_loc"=>"Oman"),
            array("country_code"=>107,"name"=>"فلسطين","name_loc"=>"Palestine"),
            array("country_code"=>108,"name"=>"قطر","name_loc"=>"Qatar"),
            array("country_code"=>109,"name"=>"الكويت","name_loc"=>"Kuwait"),
            array("country_code"=>110,"name"=>"لبنان","name_loc"=>"Lebanon"),
            array("country_code"=>111,"name"=>"اليمن","name_loc"=>"Yemen"),
            array("country_code"=>112,"name"=>"اليمن الجنوبي","name_loc"=>"Southern Yemen"),
            array("country_code"=>113,"name"=>"العربية السعودية","name_loc"=>"Saudi Arabia"),
            array("country_code"=>114,"name"=>"يمني جنوبي-السلاطين","name_loc"=>"Yemeni the sultans"),
            array("country_code"=>115,"name"=>"بني حارث","name_loc"=>"Bani Harith"),
            array("country_code"=>116,"name"=>"الكويت-بدون","name_loc"=>"Kuwait - without"),
            array("country_code"=>117,"name"=>"افراد القبائل","name_loc"=>"Member of the tribes"),
            array("country_code"=>118,"name"=>"من سكان البحرين","name_loc"=>"Residents of Bahrain"),
            array("country_code"=>119,"name"=>"قبائل مجاورة للعطفين","name_loc"=>"Tribes adj to Ataf"),
            array("country_code"=>120,"name"=>"اجنبي بجواز سعودي","name_loc"=>"AlienKSA Passprt"),
            array("country_code"=>121,"name"=>"فلسطيني بوثيقة مصرية","name_loc"=>"Palestinian Egyptian"),
            array("country_code"=>122,"name"=>"فلسطيني بوثيقةلبناني","name_loc"=>"Palestinian Lebanese"),
            array("country_code"=>123,"name"=>"فلسطيني بوثيقةاردنية","name_loc"=>"Palestinian Jordan"),
            array("country_code"=>124,"name"=>"فلسطيني بوثيقةعراقية","name_loc"=>"Palestinian Iraqi"),
            array("country_code"=>125,"name"=>"فلسطيني بوثيقة سورية","name_loc"=>"Palestinian Syria"),
            array("country_code"=>126,"name"=>"وثيقة قطريه","name_loc"=>" document Syria"),
            array("country_code"=>127,"name"=>"وثيقة عمانيه","name_loc"=>"The document Omani"),
            array("country_code"=>128,"name"=>"وثيقة اماراتيه","name_loc"=>"The document EMIRIAN"),
            array("country_code"=>129,"name"=>"وثيقة بحرينيه","name_loc"=>"Document Industry"),
            array("country_code"=>130,"name"=>"عرب ثمانية وأربعون","name_loc"=>"Arabs 48"),
            array("country_code"=>131,"name"=>"قبائل نازحة/الحليفه","name_loc"=>"Tribe/AlHal"),
            array("country_code"=>132,"name"=>"اليمن - لحج","name_loc"=>"Yemen - pilgrimage"),
            array("country_code"=>133,"name"=>"قبائل نازحة/الكويت","name_loc"=>"Tribes/ Kuwait"),
            array("country_code"=>134,"name"=>"غير كويتي","name_loc"=>"Non Kuwaiti"),
            array("country_code"=>135,"name"=>"غير بحريني","name_loc"=>"Non Bahraini"),
            array("country_code"=>136,"name"=>"غير قطري","name_loc"=>"Non Qatri"),
            array("country_code"=>137,"name"=>"غير اماراتي","name_loc"=>"Non Emriati"),
            array("country_code"=>138,"name"=>"غير عماني","name_loc"=>"Non Omani"),
            array("country_code"=>139,"name"=>"مقيم/نازح","name_loc"=>"Resident / displaced person"),
            array("country_code"=>140,"name"=>"مقيم/مولود","name_loc"=>"Resident / Child"),
            array("country_code"=>141,"name"=>"مقيم/طالب جنسية","name_loc"=>"Resident / Student Nationality"),
            array("country_code"=>142,"name"=>"مقيم/أفراد القبائل","name_loc"=>"Resident / Tribal Members"),
            array("country_code"=>143,"name"=>"مقيم/غير معروف","name_loc"=>"Resident / Unknown"),
            array("country_code"=>144,"name"=>"مقيم/لا يحمل وثيقة","name_loc"=>"Resident / does not carry a document"),
            array("country_code"=>145,"name"=>"قبيلة الصيعر","name_loc"=>"ALSAYAR"),
            array("country_code"=>146,"name"=>"المناهيل والمهرة","name_loc"=>"ALMNAHIL AND ALMAHRH"),
            array("country_code"=>201,"name"=>"تونس","name_loc"=>"Tunisia"),
            array("country_code"=>202,"name"=>"الجزائر","name_loc"=>"Algeria"),
            array("country_code"=>203,"name"=>"جيبوتى","name_loc"=>"Djibouti"),
            array("country_code"=>204,"name"=>"السودان","name_loc"=>"Sudan"),
            array("country_code"=>205,"name"=>"الصومال","name_loc"=>"Somalia"),
            array("country_code"=>206,"name"=>"ليبيا","name_loc"=>"Libya"),
            array("country_code"=>207,"name"=>"مصر","name_loc"=>"Egypt"),
            array("country_code"=>208,"name"=>"المغرب","name_loc"=>"Morocco"),
            array("country_code"=>209,"name"=>"موريتانيا","name_loc"=>"Mauritania"),
            array("country_code"=>301,"name"=>"افغانستان","name_loc"=>"Afghanistan"),
            array("country_code"=>302,"name"=>"اندونيسيا","name_loc"=>"Indonesia"),
            array("country_code"=>303,"name"=>"ايران","name_loc"=>"Iran"),
            array("country_code"=>304,"name"=>"باكستان","name_loc"=>"Pakistan"),
            array("country_code"=>305,"name"=>"بنجلاديش","name_loc"=>"Bangladesh"),
            array("country_code"=>306,"name"=>"بروني","name_loc"=>"Brunei"),
            array("country_code"=>307,"name"=>"جمهورية ميانمار","name_loc"=>"Myanmar"),
            array("country_code"=>308,"name"=>"تايلند","name_loc"=>"Thailand"),
            array("country_code"=>309,"name"=>"تركيا","name_loc"=>"Turkey"),
            array("country_code"=>310,"name"=>"جزر ملاديف","name_loc"=>"Maldives"),
            array("country_code"=>311,"name"=>"روسيا الاتحادية","name_loc"=>"Russia"),
            array("country_code"=>312,"name"=>"سنغافورة","name_loc"=>"Singapore"),
            array("country_code"=>313,"name"=>"سري لنكا","name_loc"=>"Sri Lanka"),
            array("country_code"=>314,"name"=>"الصين الوطنية","name_loc"=>"China National"),
            array("country_code"=>315,"name"=>"الفلبين","name_loc"=>"Philippines"),
            array("country_code"=>316,"name"=>"فيتنام","name_loc"=>"Vietnam"),
            array("country_code"=>317,"name"=>"كمبوديا","name_loc"=>"Cambodia"),
            array("country_code"=>318,"name"=>"كوريا الجنوبية","name_loc"=>"South Korea"),
            array("country_code"=>319,"name"=>"ماليزيا","name_loc"=>"Malaysia"),
            array("country_code"=>320,"name"=>"نيبال","name_loc"=>"Nepal"),
            array("country_code"=>321,"name"=>"الهند","name_loc"=>"India"),
            array("country_code"=>322,"name"=>"هونج كونج","name_loc"=>"HONG KONG"),
            array("country_code"=>323,"name"=>"اليابان","name_loc"=>"Japan"),
            array("country_code"=>324,"name"=>"بهوتان","name_loc"=>"Bhutan"),
            array("country_code"=>325,"name"=>"الصين الشعبية","name_loc"=>"China"),
            array("country_code"=>326,"name"=>"قبرص","name_loc"=>"Cyprus"),
            array("country_code"=>328,"name"=>"كوريا الشمالية","name_loc"=>"North Korea"),
            array("country_code"=>329,"name"=>"لاوس","name_loc"=>"Laos"),
            array("country_code"=>330,"name"=>"منغوليا","name_loc"=>"Mongolia"),
            array("country_code"=>331,"name"=>"ماكاو","name_loc"=>"Macao"),
            array("country_code"=>332,"name"=>"تركستان","name_loc"=>"Turkistan"),
            array("country_code"=>333,"name"=>"مقيم بلوشي","name_loc"=>"Resident Balushi"),
            array("country_code"=>334,"name"=>"بخارستان","name_loc"=>"Bucharest"),
            array("country_code"=>335,"name"=>"القبائل النازحة","name_loc"=>"Tribes emigrated"),
            array("country_code"=>336,"name"=>"كازاخستان","name_loc"=>"Kazakhstan"),
            array("country_code"=>337,"name"=>"ازبكستان","name_loc"=>"Uzbekistan"),
            array("country_code"=>338,"name"=>"تركمانستان","name_loc"=>"Turkmenistan"),
            array("country_code"=>339,"name"=>"طاجكستان","name_loc"=>"Tajikistan"),
            array("country_code"=>340,"name"=>"قرغيزستان","name_loc"=>"kyrgyzstan"),
            array("country_code"=>341,"name"=>"سقطرة","name_loc"=>"Socotra"),
            array("country_code"=>342,"name"=>"مهرة","name_loc"=>"Muhrah"),
            array("country_code"=>343,"name"=>"اذربيجان","name_loc"=>"Azerbaijan"),
            array("country_code"=>344,"name"=>"الشاشان","name_loc"=>"Chechnya"),
            array("country_code"=>345,"name"=>"داغستان","name_loc"=>"Dagestan"),
            array("country_code"=>346,"name"=>"انقوش","name_loc"=>"Anquosh"),
            array("country_code"=>347,"name"=>"تتارستان","name_loc"=>"Tatarstan"),
            array("country_code"=>348,"name"=>"مكررلقرغيزيا لايستخدم","name_loc"=>"Kyrgyzstan not used"),
            array("country_code"=>349,"name"=>"تيمور الشرقية","name_loc"=>"East Timor"),
            array("country_code"=>350,"name"=>"مقيم","name_loc"=>"Resident"),
            array("country_code"=>351,"name"=>"ميانمار/مقيم","name_loc"=>"Resident / Myanmar"),
            array("country_code"=>352,"name"=>"ميانمار/جواز باكستان","name_loc"=>"-"),
            array("country_code"=>353,"name"=>"ميانمار/جوازبنجلا دش","name_loc"=>"-"),
            array("country_code"=>401,"name"=>"اثيوبيا","name_loc"=>"Ethiopia"),
            array("country_code"=>402,"name"=>"اوغندة","name_loc"=>"Uganda"),
            array("country_code"=>403,"name"=>"بوتسوانا","name_loc"=>"Botswana"),
            array("country_code"=>404,"name"=>"بورندي","name_loc"=>"Burundi"),
            array("country_code"=>405,"name"=>"تشاد","name_loc"=>"Chad"),
            array("country_code"=>406,"name"=>"تنزانيا","name_loc"=>"Tanzania"),
            array("country_code"=>407,"name"=>"توجو","name_loc"=>"Togo"),
            array("country_code"=>408,"name"=>"جابون","name_loc"=>"Answer"),
            array("country_code"=>409,"name"=>"غامبيا","name_loc"=>"Gambia"),
            array("country_code"=>410,"name"=>"جزر القمر","name_loc"=>"Comoros"),
            array("country_code"=>411,"name"=>"جنوبافريقيا","name_loc"=>"South Africa"),
            array("country_code"=>412,"name"=>"ناميبيا","name_loc"=>"Namibia"),
            array("country_code"=>413,"name"=>"بنين","name_loc"=>"Benin"),
            array("country_code"=>414,"name"=>"رواندا","name_loc"=>"Rwanda"),
            array("country_code"=>415,"name"=>"زمبابوي","name_loc"=>"Zimbabwe"),
            array("country_code"=>416,"name"=>"زائير","name_loc"=>"Zaire"),
            array("country_code"=>417,"name"=>"زامبيا","name_loc"=>"Zambia"),
            array("country_code"=>418,"name"=>"ساحل العاج","name_loc"=>"Ivory Coast"),
            array("country_code"=>419,"name"=>"السنغال","name_loc"=>"Senegal"),
            array("country_code"=>420,"name"=>"سيراليون","name_loc"=>"Sierra Leone"),
            array("country_code"=>421,"name"=>"غانا","name_loc"=>"Ghana"),
            array("country_code"=>422,"name"=>"غينيا","name_loc"=>"Guinea"),
            array("country_code"=>423,"name"=>"غينيابيساو","name_loc"=>"Guinea Bissau"),
            array("country_code"=>424,"name"=>"بوركينافاسو","name_loc"=>"Burkina Faso"),
            array("country_code"=>425,"name"=>"الكاميرون","name_loc"=>"Cameroon"),
            array("country_code"=>426,"name"=>"الكونغو","name_loc"=>"Congo"),
            array("country_code"=>427,"name"=>"كينيا","name_loc"=>"Kenya"),
            array("country_code"=>428,"name"=>"ليسوتو","name_loc"=>"Lesotho"),
            array("country_code"=>429,"name"=>"ليبيريا","name_loc"=>"Liberia"),
            array("country_code"=>430,"name"=>"مالي","name_loc"=>"Mali"),
            array("country_code"=>432,"name"=>"ملاوي","name_loc"=>"Malawi"),
            array("country_code"=>433,"name"=>"موريشيوس","name_loc"=>"Mauritius"),
            array("country_code"=>434,"name"=>"موزمبيق","name_loc"=>"Mozambique"),
            array("country_code"=>435,"name"=>"نيجيريا","name_loc"=>"Nigeria"),
            array("country_code"=>436,"name"=>"النيجر","name_loc"=>"Niger"),
            array("country_code"=>437,"name"=>"افريقيا الوسطى","name_loc"=>"Central Africa"),
            array("country_code"=>438,"name"=>"انجولا","name_loc"=>"Angola"),
            array("country_code"=>439,"name"=>"الراسالاخضر","name_loc"=>"Cape Verde"),
            array("country_code"=>440,"name"=>"غينيا الاستوائية","name_loc"=>"Equatorial Guinea"),
            array("country_code"=>441,"name"=>"ملاجاسي","name_loc"=>"Mlajasi"),
            array("country_code"=>442,"name"=>"ساوتومي/برنسبى","name_loc"=>"Sao Tome/FranceBank"),
            array("country_code"=>443,"name"=>"جزر سيشل","name_loc"=>"Seychelles Islands"),
            array("country_code"=>444,"name"=>"سوزيلاند","name_loc"=>"Swaziland"),
            array("country_code"=>445,"name"=>"بوفثاتسوانا","name_loc"=>"Bovthatswana"),
            array("country_code"=>446,"name"=>"رينيون","name_loc"=>"Reunion"),
            array("country_code"=>447,"name"=>"ترانسكي","name_loc"=>"Transkei"),
            array("country_code"=>448,"name"=>"فيندا","name_loc"=>"Venda"),
            array("country_code"=>449,"name"=>"ارتيريا","name_loc"=>"Eritrea"),
            array("country_code"=>450,"name"=>"دول افريقية اخري","name_loc"=>"Other African States"),
            array("country_code"=>451,"name"=>"سانت هيلانة","name_loc"=>"Saint Helena"),
            array("country_code"=>452,"name"=>"جزيرةمايوت","name_loc"=>"Comorian island"),
            array("country_code"=>453,"name"=>"جمهورية جنوب السودان","name_loc"=>"Republic of South"),
            array("country_code"=>454,"name"=>"كاب فيرد","name_loc"=>"CAPE VERDE"),
            array("country_code"=>501,"name"=>"اسبانيا","name_loc"=>"Spain"),
            array("country_code"=>502,"name"=>"البانيا","name_loc"=>"Albania"),
            array("country_code"=>503,"name"=>"المانيا","name_loc"=>"Germany"),
            array("country_code"=>504,"name"=>"ايرلندا","name_loc"=>"Ireland"),
            array("country_code"=>505,"name"=>"ايطاليا","name_loc"=>"Italy"),
            array("country_code"=>506,"name"=>"المملكة المتحدة","name_loc"=>"United Kingdom"),
            array("country_code"=>507,"name"=>"البرتغال","name_loc"=>"Portugal"),
            array("country_code"=>508,"name"=>"بلغاريا","name_loc"=>"Bulgaria"),
            array("country_code"=>509,"name"=>"بلجيكا","name_loc"=>"Belgium"),
            array("country_code"=>510,"name"=>"بولندا","name_loc"=>"Poland"),
            array("country_code"=>511,"name"=>"رمزقديم تشكوسلوفاكيا","name_loc"=>"old to Czechoslovak"),
            array("country_code"=>512,"name"=>"الدانمارك","name_loc"=>"Denmark"),
            array("country_code"=>513,"name"=>"رومانيا","name_loc"=>"Romania"),
            array("country_code"=>514,"name"=>"السويد","name_loc"=>"Sweden"),
            array("country_code"=>515,"name"=>"سويسرا","name_loc"=>"Switzerland"),
            array("country_code"=>516,"name"=>"فرنسا","name_loc"=>"France"),
            array("country_code"=>517,"name"=>"فنلندا","name_loc"=>"Finland"),
            array("country_code"=>518,"name"=>"صربيا","name_loc"=>"SERBIA"),
            array("country_code"=>519,"name"=>"هولندا","name_loc"=>"Netherlands"),
            array("country_code"=>520,"name"=>"يوغسلافيا","name_loc"=>"Yugoslavia"),
            array("country_code"=>521,"name"=>"اليونان","name_loc"=>"Greece"),
            array("country_code"=>522,"name"=>"اندورا","name_loc"=>"Andorra"),
            array("country_code"=>523,"name"=>"النمسا","name_loc"=>"Austria"),
            array("country_code"=>524,"name"=>"الجبل الأ سود","name_loc"=>"MONTENEGRO"),
            array("country_code"=>525,"name"=>"هنغاريا","name_loc"=>"Hungary"),
            array("country_code"=>526,"name"=>"ايسلندا","name_loc"=>"Iceland"),
            array("country_code"=>527,"name"=>"ليختنشتين","name_loc"=>"Liechtenstein"),
            array("country_code"=>528,"name"=>"لوكسمبورغ","name_loc"=>"Luxembourg"),
            array("country_code"=>529,"name"=>"مالطا","name_loc"=>"Malta"),
            array("country_code"=>530,"name"=>"موناكو","name_loc"=>"Monaco"),
            array("country_code"=>531,"name"=>"النرويج","name_loc"=>"Norway"),
            array("country_code"=>532,"name"=>"سان مورينو","name_loc"=>"San Moreno"),
            array("country_code"=>533,"name"=>"مدينة الفاتيكان","name_loc"=>"Vatican City"),
            array("country_code"=>534,"name"=>"جبل طارق","name_loc"=>"Gibraltar"),
            array("country_code"=>536,"name"=>"اوكرانيا","name_loc"=>"Ukraine"),
            array("country_code"=>537,"name"=>"روسيا البيضاء","name_loc"=>"Byelorussia"),
            array("country_code"=>539,"name"=>"ارمينيا","name_loc"=>"Armenia"),
            array("country_code"=>540,"name"=>"مولدافيا","name_loc"=>"Moldova"),
            array("country_code"=>541,"name"=>"جورجيا","name_loc"=>"Georgia"),
            array("country_code"=>542,"name"=>"ليتوانيا","name_loc"=>"Lithuania"),
            array("country_code"=>543,"name"=>"استونيا","name_loc"=>"Estonia"),
            array("country_code"=>544,"name"=>"لاتفيا","name_loc"=>"Latvia"),
            array("country_code"=>545,"name"=>"البوسنة والهرسك","name_loc"=>"Bosnia / Herzegovina"),
            array("country_code"=>546,"name"=>"كرواتيا","name_loc"=>"Croatia"),
            array("country_code"=>547,"name"=>"سلوفينيا","name_loc"=>"Slovenia"),
            array("country_code"=>548,"name"=>"صربيا والجبل الأسود","name_loc"=>"Serbia / Montenegro"),
            array("country_code"=>549,"name"=>"مقدونيا","name_loc"=>"Macedonia"),
            array("country_code"=>550,"name"=>"كوسوفوا","name_loc"=>"Kosovo"),
            array("country_code"=>551,"name"=>"رمزقديم للجبل الاسود","name_loc"=>"code to Montenegro"),
            array("country_code"=>552,"name"=>"تشيك","name_loc"=>"CZECH REPUBLIC"),
            array("country_code"=>553,"name"=>"سلوفاكيا","name_loc"=>"Slovakia"),
            array("country_code"=>554,"name"=>"جزر فيرو","name_loc"=>"Faroe Islands"),
            array("country_code"=>555,"name"=>"ميتروبوليتان فرنسية","name_loc"=>"FRANCE METROPOLITAN"),
            array("country_code"=>601,"name"=>"الولاياتالمتحدة","name_loc"=>"United States"),
            array("country_code"=>602,"name"=>"الارجنتين","name_loc"=>"Argentina"),
            array("country_code"=>603,"name"=>"بربادوس","name_loc"=>"Barbados"),
            array("country_code"=>604,"name"=>"البرازيل","name_loc"=>"Brazil"),
            array("country_code"=>605,"name"=>"بنما","name_loc"=>"Panama"),
            array("country_code"=>606,"name"=>"ترينداد وتوباجو","name_loc"=>"Trinidad and Tobago"),
            array("country_code"=>607,"name"=>"جامايكا","name_loc"=>"Jamaica"),
            array("country_code"=>608,"name"=>"جوانا","name_loc"=>"Joanna"),
            array("country_code"=>609,"name"=>"فنزويلا","name_loc"=>"Venezuela"),
            array("country_code"=>610,"name"=>"كندا","name_loc"=>"Canada"),
            array("country_code"=>611,"name"=>"كولمبيا","name_loc"=>"Columbia"),
            array("country_code"=>612,"name"=>"جزر البهاما","name_loc"=>"Bahamas"),
            array("country_code"=>613,"name"=>"كوستاريكا","name_loc"=>"Costa Rica"),
            array("country_code"=>614,"name"=>"كوبا","name_loc"=>"Cuba"),
            array("country_code"=>615,"name"=>"دومينيكا","name_loc"=>"Dominica"),
            array("country_code"=>616,"name"=>"جمهورية دمينكان","name_loc"=>"Republic Dominica"),
            array("country_code"=>617,"name"=>"السلفادور","name_loc"=>"El Salvador"),
            array("country_code"=>618,"name"=>"جرانادا","name_loc"=>"Granada"),
            array("country_code"=>619,"name"=>"جواتيمالا","name_loc"=>"Guatemala"),
            array("country_code"=>620,"name"=>"هايتي","name_loc"=>"Haiti"),
            array("country_code"=>621,"name"=>"هوندوراس","name_loc"=>"Honduras"),
            array("country_code"=>622,"name"=>"المكسيك","name_loc"=>"Mexico"),
            array("country_code"=>623,"name"=>"نيكاراجوا","name_loc"=>"Nicaragua"),
            array("country_code"=>624,"name"=>"سانتلوسيا","name_loc"=>"Saint Lucia"),
            array("country_code"=>625,"name"=>"سان فينسنت","name_loc"=>"Saintt Vincent"),
            array("country_code"=>626,"name"=>"بوليفيا","name_loc"=>"Bolivia"),
            array("country_code"=>627,"name"=>"شيلي","name_loc"=>"Chile"),
            array("country_code"=>628,"name"=>"اكوادور","name_loc"=>"Ecuador"),
            array("country_code"=>629,"name"=>"باراجواي","name_loc"=>"Paraguay"),
            array("country_code"=>630,"name"=>"بيرو","name_loc"=>"Peru"),
            array("country_code"=>631,"name"=>"سورينام","name_loc"=>"Suriname"),
            array("country_code"=>632,"name"=>"اوراجواي","name_loc"=>"Orajoa"),
            array("country_code"=>633,"name"=>"سبييري وميكويلن","name_loc"=>"Saint Pierre Miquel"),
            array("country_code"=>634,"name"=>"جرينلاند","name_loc"=>"Greenland"),
            array("country_code"=>635,"name"=>"بيليز","name_loc"=>"Belize"),
            array("country_code"=>636,"name"=>"بيرمودا","name_loc"=>"Bermda"),
            array("country_code"=>637,"name"=>"ج التركوالقوقاز","name_loc"=>"Turk/Caucasus Island"),
            array("country_code"=>638,"name"=>"سان كريستوفرنيفز","name_loc"=>"San Cristovernivz"),
            array("country_code"=>639,"name"=>"انجويلا","name_loc"=>"Anguilla"),
            array("country_code"=>640,"name"=>"انتيكوا","name_loc"=>"Antiques"),
            array("country_code"=>641,"name"=>"ج فيرجن البريطانية","name_loc"=>"British Virgin"),
            array("country_code"=>642,"name"=>"جزر كايمون","name_loc"=>"Cayman Islands"),
            array("country_code"=>643,"name"=>"مونتسيرات","name_loc"=>"Monte Sirat"),
            array("country_code"=>644,"name"=>"جيودي لوب","name_loc"=>"Gyude Lube"),
            array("country_code"=>645,"name"=>"مارتينيكو","name_loc"=>"Martinico"),
            array("country_code"=>646,"name"=>"عروبا","name_loc"=>"Arabism"),
            array("country_code"=>647,"name"=>"بونيري","name_loc"=>"Bonaire"),
            array("country_code"=>648,"name"=>"كيوراكو","name_loc"=>"Curako"),
            array("country_code"=>649,"name"=>"سان استاتيوس","name_loc"=>"San Astatios"),
            array("country_code"=>650,"name"=>"سابا","name_loc"=>"Saba"),
            array("country_code"=>651,"name"=>"سان مارتين","name_loc"=>"San Martin"),
            array("country_code"=>652,"name"=>"بورتوريكو","name_loc"=>"Puerto Rico"),
            array("country_code"=>653,"name"=>"ج فيرجن الامريكية","name_loc"=>"Virgin Islands of US"),
            array("country_code"=>654,"name"=>"جزر فاكلاند","name_loc"=>"Falkland Islands"),
            array("country_code"=>655,"name"=>"جيانا الفرنسية","name_loc"=>"French Guyana"),
            array("country_code"=>656,"name"=>"الامم المتحدة","name_loc"=>"United Nations"),
            array("country_code"=>657,"name"=>"جزر كوك","name_loc"=>"Cook Islands"),
            array("country_code"=>659,"name"=>"باربودا","name_loc"=>"Barbuda"),
            array("country_code"=>660,"name"=>"انتيل الهولندية","name_loc"=>"NETHERLANDS ANTILLES"),
            array("country_code"=>661,"name"=>"جزر كوكوس","name_loc"=>"COCOS ISLAND"),
            array("country_code"=>662,"name"=>"البريطانية في المحيط","name_loc"=>"BRITISH INDIAN OCEAN"),
            array("country_code"=>663,"name"=>"سانت كيتسونافيس","name_loc"=>"SAINT KITTS & NEVIS"),
            array("country_code"=>664,"name"=>"جنوب جورجيا","name_loc"=>"SOUTH GEORGIA"),
            array("country_code"=>701,"name"=>"استراليا","name_loc"=>"Australia"),
            array("country_code"=>702,"name"=>"نيوزيلندا","name_loc"=>"New Zealand"),
            array("country_code"=>703,"name"=>"بابوا نيوغينا","name_loc"=>"Papua yoga"),
            array("country_code"=>704,"name"=>"نيو","name_loc"=>"New"),
            array("country_code"=>705,"name"=>"انتاركتيكا","name_loc"=>"Antarctica"),
            array("country_code"=>706,"name"=>"جزر نورفولك","name_loc"=>"Norfolk Island"),
            array("country_code"=>707,"name"=>"توكيلاو","name_loc"=>"Tokelau"),
            array("country_code"=>708,"name"=>"جزيرةكريسماس","name_loc"=>"Christmas Island"),
            array("country_code"=>709,"name"=>"جزيرةكوكو-كيلنج","name_loc"=>"koko Island- Kellenj"),
            array("country_code"=>710,"name"=>"فرنسا الجنوب القطبية","name_loc"=>"FRENCH SOUTH"),
            array("country_code"=>711,"name"=>"جزيرة هيرد وماكدونلد","name_loc"=>"HEARD DONALD ISLANDS"),
            array("country_code"=>712,"name"=>"جزر بيتكايرن","name_loc"=>"PITCAIRN ISLANDS"),
            array("country_code"=>801,"name"=>"جزر فيجي","name_loc"=>"Fiji Islands"),
            array("country_code"=>802,"name"=>"كيريباتي","name_loc"=>"Kiribati"),
            array("country_code"=>803,"name"=>"نورو","name_loc"=>"Nauru"),
            array("country_code"=>804,"name"=>"جزر سليمان","name_loc"=>"Solomon Islands"),
            array("country_code"=>805,"name"=>"تونجا","name_loc"=>"Tonga"),
            array("country_code"=>806,"name"=>"توفالو","name_loc"=>"Tuvalu"),
            array("country_code"=>807,"name"=>"فانيوتو","name_loc"=>"Vanuoto"),
            array("country_code"=>808,"name"=>"ساموا الغربية","name_loc"=>"Western Samoa"),
            array("country_code"=>809,"name"=>"ساموا الامريكية","name_loc"=>"American Samoa"),
            array("country_code"=>810,"name"=>"جوام","name_loc"=>"Guam"),
            array("country_code"=>811,"name"=>"جزر ماريانا","name_loc"=>"Mariana Islands"),
            array("country_code"=>812,"name"=>"ميكرونيسيا","name_loc"=>"Micronesia"),
            array("country_code"=>813,"name"=>"جزر ماريشال","name_loc"=>"Marechal Islands"),
            array("country_code"=>814,"name"=>"بيلو","name_loc"=>"Belo"),
            array("country_code"=>815,"name"=>"بولينيسياالفرنسية","name_loc"=>"French Polynesia"),
            array("country_code"=>816,"name"=>"جزر والسوفوتونا","name_loc"=>"Islands Wallis"),
            array("country_code"=>817,"name"=>"كاليدونيا الجديد","name_loc"=>"New Caledonia"),
            array("country_code"=>818,"name"=>"مدغشقر","name_loc"=>"Madagascar"),
            array("country_code"=>819,"name"=>"قبيلة بالعبيد","name_loc"=>"Balobid"),
            array("country_code"=>820,"name"=>" قبيلة النسي","name_loc"=>"NULL"),
            array("country_code"=>821,"name"=>"قبائل مجاورة للعبر","name_loc"=>"TRIBES ADJACENT"),
            array("country_code"=>822,"name"=>"قبيلة الحرث","name_loc"=>"QABILA ALHARS"),
            array("country_code"=>823,"name"=>"قبيلة نهد","name_loc"=>"QABILA NAHD"),
            array("country_code"=>824,"name"=>"جزر مينور","name_loc"=>"US MINOR ISLANDS"),
            array("country_code"=>825,"name"=>"مقيم اجنبي - الاشاجعة","name_loc"=>"Foreign resident - Lying"),
            array("country_code"=>826,"name"=>"مقيم اجنبي - العدوان","name_loc"=>"Foreign Resident - Aggression"),
            array("country_code"=>900,"name"=>"غير معروف","name_loc"=>"Unknown"),
            array("country_code"=>901,"name"=>"اخرى","name_loc"=>"OTHER")
          );

          DB::table('countries')->insert($countries);

    }
}
